# Generated by Django 3.0.8 on 2020-07-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_detail',
            old_name='reffer_by',
            new_name='reffered_by',
        ),
    ]
