# Generated by Django 3.0.8 on 2020-07-13 09:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient_detail', '0002_auto_20200712_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_detail',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True),
        ),
    ]
